### ISSUE TITLE
Obsolete CN Tile model and ngrok tunnel start error

### ISSUE THREAD

**Issue by kremlevmv** [Linaqruf/vladmandic-webui-colab#1]
1. CN Tile model "control_v11u__sd15_tile" is obsolete.  Can you please update it to "control_v11f1e__sd15_tile"? 
2. I tried to start ngrok tunnel and got an error about cloudflare. I did everything right - chose ngrok option and paste my ngrok token. So I deleted this line and started the cell again. It worked just fine without that line.
![изображение](https://user-images.githubusercontent.com/132686332/236497677-d1d61ff5-f99b-4c84-b4ac-8150b031b5ad.png)

**Comment by Linaqruf** [comment]
Thank you for bug report, and sorry for the late reply 
I forgot to install pycloudflared. I fix it by deleting old cloudflared code and use https://github.com/Bing-su/sd-webui-tunnels/ instead.
